export interface LanguageEntry {
  name: string;
  code: string;
  country: {
    code: string;
    name: string;
    emoji: string;
  };
}

/** For VGJR api translate */
function lang(...data: string[]): LanguageEntry {
  return {
    name: data[0],
    code: data[1],
    country: {
      code: data[2],
      name: data[3],
      emoji: data[4],
    },
  };
}
export const Languages: LanguageEntry[] = [
  lang("Abkhaz", "ab", "GE", "Georgia", "🇬🇪"),
  lang("Acehnese", "ace", "ID", "Indonesia", "🇮🇩"),
  lang("Acholi", "ach", "UG", "Uganda", "🇺🇬"),
  lang("Afar", "aa", "ET", "Ethiopia", "🇪🇹"),
  lang("Afrikaans", "af", "ZA", "South Africa", "🇿🇦"),
  lang("Albanian", "sq", "AL", "Albania", "🇦🇱"),
  lang("Alur", "alz", "UG", "Uganda", "🇺🇬"),
  lang("Amharic", "am", "ET", "Ethiopia", "🇪🇹"),
  lang("Arabic", "ar", "SA", "Saudi Arabia", "🇸🇦"),
  lang("Armenian", "hy", "AM", "Armenia", "🇦🇲"),
  lang("Assamese", "as", "IN", "India", "🇮🇳"),
  lang("Avar", "av", "RU", "Russia", "🇷🇺"),
  lang("Awadhi", "awa", "IN", "India", "🇮🇳"),
  lang("Aymara", "ay", "BO", "Bolivia", "🇧🇴"),
  lang("Azerbaijani", "az", "AZ", "Azerbaijan", "🇦🇿"),
  lang("Balinese", "ban", "ID", "Indonesia", "🇮🇩"),
  lang("Bambara", "bm", "ML", "Mali", "🇲🇱"),
  lang("Bashkir", "ba", "RU", "Russia", "🇷🇺"),
  lang("Basque", "eu", "ES", "Spain", "🇪🇸"),
  lang("Batak Karo", "btx", "ID", "Indonesia", "🇮🇩"),
  lang("Batak Simalungun", "bts", "ID", "Indonesia", "🇮🇩"),
  lang("Batak Toba", "bbc", "ID", "Indonesia", "🇮🇩"),
  lang("Belarusian", "be", "BY", "Belarus", "🇧🇾"),
  lang("Bengali", "bn", "BD", "Bangladesh", "🇧🇩"),
  lang("Bhojpuri", "bho", "IN", "India", "🇮🇳"),
  lang("Bikol", "bik", "PH", "Philippines", "🇵🇭"),
  lang("Bosnian", "bs", "BA", "Bosnia and Herzegovina", "🇧🇦"),
  lang("Breton", "br", "FR", "France", "🇫🇷"),
  lang("Bulgarian", "bg", "BG", "Bulgaria", "🇧🇬"),
  lang("Buryat", "bua", "RU", "Russia", "🇷🇺"),
  lang("Cantonese", "yue", "HK", "Hong Kong", "🇭🇰"),
  lang("Catalan", "ca", "ES", "Spain", "🇪🇸"),
  lang("Cebuano", "ceb", "PH", "Philippines", "🇵🇭"),
  lang("Chamorro", "ch", "GU", "Guam", "🇬🇺"),
  lang("Chechen", "ce", "RU", "Russia", "🇷🇺"),
  lang("Chichewa", "ny", "MW", "Malawi", "🇲🇼"),
  lang("Chinese (Simplified)", "zh-CN", "CN", "China", "🇨🇳"),
  lang("Chinese (Traditional)", "zh-TW", "TW", "Taiwan", "🇹🇼"),
  lang("Chuvash", "cv", "RU", "Russia", "🇷🇺"),
  lang("Corsican", "co", "FR", "France", "🇫🇷"),
  lang("Crimean Tatar", "crh", "UA", "Ukraine", "🇺🇦"),
  lang("Croatian", "hr", "HR", "Croatia", "🇭🇷"),
  lang("Czech", "cs", "CZ", "Czechia", "🇨🇿"),
  lang("Danish", "da", "DK", "Denmark", "🇩🇰"),
  lang("Dhivehi", "dv", "MV", "Maldives", "🇲🇻"),
  lang("Dininkka", "din", "SS", "South Sudan", "🇸🇸"),
  lang("Dogri", "doi", "IN", "India", "🇮🇳"),
  lang("Dombe", "dom", "ZM", "Zambia", "🇿🇲"),
  lang("Dutch", "nl", "NL", "Netherlands", "🇳🇱"),
  lang("Dyula", "dyu", "CI", "Côte d'Ivoire", "🇨🇮"),
  lang("Dzongkha", "dz", "BT", "Bhutan", "🇧🇹"),
  lang("English", "en", "GB", "United Kingdom", "🇬🇧"),
  lang("Esperanto", "eo", "UN", "International", "🌐"),
  lang("Estonian", "et", "EE", "Estonia", "🇪🇪"),
  lang("Ewe", "ee", "GH", "Ghana", "🇬🇭"),
  lang("Faroese", "fo", "FO", "Faroe Islands", "🇫🇴"),
  lang("Fijian", "fj", "FJ", "Fiji", "🇫🇯"),
  lang("Filipino", "fil", "PH", "Philippines", "🇵🇭"),
  lang("Finnish", "fi", "FI", "Finland", "🇫🇮"),
  lang("French", "fr", "FR", "France", "🇫🇷"),
  lang("French (Canada)", "fr-CA", "CA", "Canada", "🇨🇦"),
  lang("Frisian", "fy", "NL", "Netherlands", "🇳🇱"),
  lang("Friulian", "fur", "IT", "Italy", "🇮🇹"),
  lang("Fulani", "ff", "GN", "Guinea", "🇬🇳"),
  lang("Ga", "gaa", "GH", "Ghana", "🇬🇭"),
  lang("Galician", "gl", "ES", "Spain", "🇪🇸"),
  lang("Georgian", "ka", "GE", "Georgia", "🇬🇪"),
  lang("German", "de", "DE", "Germany", "🇩🇪"),
  lang("Greek", "el", "GR", "Greece", "🇬🇷"),
  lang("Guarani", "gn", "PY", "Paraguay", "🇵🇾"),
  lang("Gujarati", "gu", "IN", "India", "🇮🇳"),
  lang("Haitian Creole", "ht", "HT", "Haiti", "🇭🇹"),
  lang("Hakha Chin", "cnh", "MM", "Myanmar", "🇲🇲"),
  lang("Hausa", "ha", "NG", "Nigeria", "🇳🇬"),
  lang("Hawaiian", "haw", "US", "United States", "🇺🇸"),
  lang("Hebrew", "he", "IL", "Israel", "🇮🇱"),
  lang("Hindi", "hi", "IN", "India", "🇮🇳"),
  lang("Hmong", "hmn", "LA", "Laos", "🇱🇦"),
  lang("Hungarian", "hu", "HU", "Hungary", "🇭🇺"),
  lang("Hunsrik", "hrx", "BR", "Brazil", "🇧🇷"),
  lang("Iban", "iba", "MY", "Malaysia", "🇲🇾"),
  lang("Icelandic", "is", "IS", "Iceland", "🇮🇸"),
  lang("Igbo", "ig", "NG", "Nigeria", "🇳🇬"),
  lang("Ilocano", "ilo", "PH", "Philippines", "🇵🇭"),
  lang("Indonesian", "id", "ID", "Indonesia", "🇮🇩"),
  lang("Irish", "ga", "IE", "Ireland", "🇮🇪"),
  lang("Italian", "it", "IT", "Italy", "🇮🇹"),
  lang("Japanese", "ja", "JP", "Japan", "🇯🇵"),
  lang("Javanese", "jv", "ID", "Indonesia", "🇮🇩"),
  lang("Jingpo", "kac", "MM", "Myanmar", "🇲🇲"),
  lang("Kalaallisut", "kl", "GL", "Greenland", "🇬🇱"),
  lang("Kannada", "kn", "IN", "India", "🇮🇳"),
  lang("Kanuri", "kr", "NG", "Nigeria", "🇳🇬"),
  lang("Kapampangan", "pam", "PH", "Philippines", "🇵🇭"),
  lang("Kazakh", "kk", "KZ", "Kazakhstan", "🇰🇿"),
  lang("Khasi", "kha", "IN", "India", "🇮🇳"),
  lang("Khmer", "km", "KH", "Cambodia", "🇰🇭"),
  lang("Kiga", "cgg", "UG", "Uganda", "🇺🇬"),
  lang("Kikongo", "kg", "CD", "DR Congo", "🇨🇩"),
  lang("Kinyarwanda", "rw", "RW", "Rwanda", "🇷🇼"),
  lang("Kituba", "ktu", "CD", "DR Congo", "🇨🇩"),
  lang("Kokborok", "trp", "IN", "India", "🇮🇳"),
  lang("Konkani", "gom", "IN", "India", "🇮🇳"),
  lang("Korean", "ko", "KR", "South Korea", "🇰🇷"),
  lang("Krio", "kri", "SL", "Sierra Leone", "🇸🇱"),
  lang("Kurdish (Kurmanji)", "ku", "TR", "Turkey", "🇹🇷"),
  lang("Kurdish (Sorani)", "ckb", "IQ", "Iraq", "🇮🇶"),
  lang("Kyrgyz", "ky", "KG", "Kyrgyzstan", "🇰🇬"),
  lang("Lao", "lo", "LA", "Laos", "🇱🇦"),
  lang("Latavian", "lv", "LV", "Latvia", "🇱🇻"),
  lang("Ligurian", "lij", "IT", "Italy", "🇮🇹"),
  lang("Limburgish", "li", "NL", "Netherlands", "🇳🇱"),
  lang("Lingala", "ln", "CD", "DR Congo", "🇨🇩"),
  lang("Lithuanian", "lt", "LT", "Lithuania", "🇱🇹"),
  lang("Lombard", "lmo", "IT", "Italy", "🇮🇹"),
  lang("Luganda", "lg", "UG", "Uganda", "🇺🇬"),
  lang("Luo", "luo", "KE", "Kenya", "🇰🇪"),
  lang("Luxembourgish", "lb", "LU", "Luxembourg", "🇱🇺"),
  lang("Macedonian", "mk", "MK", "North Macedonia", "🇲🇰"),
  lang("Madurese", "mad", "ID", "Indonesia", "🇮🇩"),
  lang("Magahi", "mag", "IN", "India", "🇮🇳"),
  lang("Maithili", "mai", "IN", "India", "🇮🇳"),
  lang("Makassar", "mak", "ID", "Indonesia", "🇮🇩"),
  lang("Malagasy", "mg", "MG", "Madagascar", "🇲🇬"),
  lang("Malay", "ms", "MY", "Malaysia", "🇲🇾"),
  lang("Malayalam", "ml", "IN", "India", "🇮🇳"),
  lang("Maltese", "mt", "MT", "Malta", "🇲🇹"),
  lang("Mam", "mam", "GT", "Guatemala", "🇬🇹"),
  lang("Manx", "gv", "IM", "Isle of Man", "🇮🇲"),
  lang("Maori", "mi", "NZ", "New Zealand", "🇳🇿"),
  lang("Marathi", "mr", "IN", "India", "🇮🇳"),
  lang("Marshallese", "mh", "MH", "Marshall Islands", "🇲🇭"),
  lang("Marwadi", "mwr", "IN", "India", "🇮🇳"),
  lang("Mauritian Creole", "mfe", "MU", "Mauritius", "🇲🇺"),
  lang("Meiteilon (Manipuri)", "mni-Mtei", "IN", "India", "🇮🇳"),
  lang("Minangkabau", "min", "ID", "Indonesia", "🇮🇩"),
  lang("Mizo", "lus", "IN", "India", "🇮🇳"),
  lang("Mongolian", "mn", "MN", "Mongolia", "🇲🇳"),
  lang("Myanmar (Burmese)", "my", "MM", "Myanmar", "🇲🇲"),
  lang("Nahuatl", "nah", "MX", "Mexico", "🇲🇽"),
  lang("Ndau", "ndc", "ZW", "Zimbabwe", "🇿🇼"),
  lang("Ndebele (South)", "nr", "ZA", "South Africa", "🇿🇦"),
  lang("Nepalbhasha (Newari)", "new", "NP", "Nepal", "🇳🇵"),
  lang("Nepali", "ne", "NP", "Nepal", "🇳🇵"),
  lang("NKo", "nko", "GN", "Guinea", "🇬🇳"),
  lang("Norwegian", "no", "NO", "Norway", "🇳🇴"),
  lang("Nuer", "nus", "SS", "South Sudan", "🇸🇸"),
  lang("Occitan", "oc", "FR", "France", "🇫🇷"),
  lang("Odia (Oriya)", "or", "IN", "India", "🇮🇳"),
  lang("Oromo", "om", "ET", "Ethiopia", "🇪🇹"),
  lang("Ossetian", "os", "RU", "Russia", "🇷🇺"),
  lang("Pangasinan", "pag", "PH", "Philippines", "🇵🇭"),
  lang("Papiamento", "pap", "AW", "Aruba", "🇦🇼"),
  lang("Pashto", "ps", "AF", "Afghanistan", "🇦🇫"),
  lang("Persian", "fa", "IR", "Iran", "🇮🇷"),
  lang("Polish", "pl", "PL", "Poland", "🇵🇱"),
  lang("Portuguese (Brazil)", "pt-BR", "BR", "Brazil", "🇧🇷"),
  lang("Portuguese (Portugal)", "pt-PT", "PT", "Portugal", "🇵🇹"),
  lang("Punjabi (Gurmukhi)", "pa", "IN", "India", "🇮🇳"),
  lang("Punjabi (Shahmukhi)", "pa-Arab", "PK", "Pakistan", "🇵🇰"),
  lang("Quechua", "qu", "PE", "Peru", "🇵🇪"),
  lang("Qʼeqchiʼ", "kek", "GT", "Guatemala", "🇬🇹"),
  lang("Romani", "rom", "RO", "Romania", "🇷🇴"),
  lang("Romanian", "ro", "RO", "Romania", "🇷🇴"),
  lang("Rundi", "rn", "BI", "Burundi", "🇧🇮"),
  lang("Russian", "ru", "RU", "Russia", "🇷🇺"),
  lang("Samoan", "sm", "WS", "Samoa", "🇼🇸"),
  lang("Sango", "sg", "CF", "Central African Republic", "🇨🇫"),
  lang("Sanskrit", "sa", "IN", "India", "🇮🇳"),
  lang("Santali", "sat", "IN", "India", "🇮🇳"),
  lang("Scots Gaelic", "gd", "GB", "United Kingdom", "🇬🇧"),
  lang("Sepedi", "nso", "ZA", "South Africa", "🇿🇦"),
  lang("Serbian", "sr", "RS", "Serbia", "🇷🇸"),
  lang("Sesotho", "st", "LS", "Lesotho", "🇱🇸"),
  lang("Seychellois Creole", "crs", "SC", "Seychelles", "🇸🇨"),
  lang("Shan", "shn", "MM", "Myanmar", "🇲🇲"),
  lang("Shona", "sn", "ZW", "Zimbabwe", "🇿🇼"),
  lang("Sicilian", "scn", "IT", "Italy", "🇮🇹"),
  lang("Silesian", "szl", "PL", "Poland", "🇵🇱"),
  lang("Sindhi", "sd", "PK", "Pakistan", "🇵🇰"),
  lang("Sinhala", "si", "LK", "Sri Lanka", "🇱🇰"),
  lang("Slovak", "sk", "SK", "Slovakia", "🇸🇰"),
  lang("Slovenian", "sl", "SI", "Slovenia", "🇸🇮"),
  lang("Somali", "so", "SO", "Somalia", "🇸🇴"),
  lang("Spanish", "es", "ES", "Spain", "🇪🇸"),
  lang("Sundanese", "su", "ID", "Indonesia", "🇮🇩"),
  lang("Susu", "sus", "GN", "Guinea", "🇬🇳"),
  lang("Swahili", "sw", "TZ", "Tanzania", "🇹🇿"),
  lang("Swati", "ss", "SZ", "Eswatini", "🇸🇿"),
  lang("Swedish", "sv", "SE", "Sweden", "🇸🇪"),
  lang("Tahitian", "ty", "PF", "French Polynesia", "🇵🇫"),
  lang("Tajik", "tg", "TJ", "Tajikistan", "🇹🇯"),
  lang("Tamazight", "tzm", "MA", "Morocco", "🇲🇦"),
  lang("Tamazight (Tifinagh)", "ber-Tfng", "MA", "Morocco", "🇲🇦"),
  lang("Tamil", "ta", "IN", "India", "🇮🇳"),
  lang("Tatar", "tt", "RU", "Russia", "🇷🇺"),
  lang("Telugu", "te", "IN", "India", "🇮🇳"),
  lang("Tetum", "tet", "TL", "Timor-Leste", "🇹🇱"),
  lang("Thai", "th", "TH", "Thailand", "🇹🇭"),
  lang("Tibetan", "bo", "CN", "China", "🇨🇳"),
  lang("Tigrinya", "ti", "ER", "Eritrea", "🇪🇷"),
  lang("Tiv", "tiv", "NG", "Nigeria", "🇳🇬"),
  lang("Tok Pisin", "tpi", "PG", "Papua New Guinea", "🇵🇬"),
  lang("Tongan", "to", "TO", "Tonga", "🇹🇴"),
  lang("Tsonga", "ts", "ZA", "South Africa", "🇿🇦"),
  lang("Tswana", "tn", "BW", "Botswana", "🇧🇼"),
  lang("Tulu", "tcy", "IN", "India", "🇮🇳"),
  lang("Tumbuka", "tum", "MW", "Malawi", "🇲🇼"),
  lang("Turkish", "tr", "TR", "Turkey", "🇹🇷"),
  lang("Turkmen", "tk", "TM", "Turkmenistan", "🇹🇲"),
  lang("Tuvan", "tyv", "RU", "Russia", "🇷🇺"),
  lang("Twi", "ak", "GH", "Ghana", "🇬🇭"),
  lang("Udmurt", "udm", "RU", "Russia", "🇷🇺"),
  lang("Ukrainian", "uk", "UA", "Ukraine", "🇺🇦"),
  lang("Urdu", "ur", "PK", "Pakistan", "🇵🇰"),
  lang("Uyghur", "ug", "CN", "China", "🇨🇳"),
  lang("Uzbek", "uz", "UZ", "Uzbekistan", "🇺🇿"),
  lang("Venda", "ve", "ZA", "South Africa", "🇿🇦"),
  lang("Venetian", "vec", "IT", "Italy", "🇮🇹"),
  lang("Vietnamese", "vi", "VN", "Vietnam", "🇻🇳"),
  lang("Waray", "war", "PH", "Philippines", "🇵🇭"),
  lang("Welsh", "cy", "GB", "United Kingdom", "🇬🇧"),
  lang("Wolof", "wo", "SN", "Senegal", "🇸🇳"),
  lang("Xhosa", "xh", "ZA", "South Africa", "🇿🇦"),
  lang("Yakut", "sah", "RU", "Russia", "🇷🇺"),
  lang("Yiddish", "yi", "IL", "Israel", "🇮🇱"),
  lang("Yoruba", "yo", "NG", "Nigeria", "🇳🇬"),
  lang("Yucatec Maya", "yua", "MX", "Mexico", "🇲🇽"),
  lang("Zapotec", "zap", "MX", "Mexico", "🇲🇽"),
  lang("Zulu", "zu", "ZA", "South Africa", "🇿🇦"),
];
